databases:
- name: asg-rinzler
  databaseName: asg-rinzler
  user: asg-rinzler
  plan: standard 

services:
- type: web
  name: asg-rinzler
  env: docker
  dockerfilePath: ./server/Dockerfile
  dockerContext: ./server
  autoDeploy: false
  envVars:
  - key: IS_BEHIND_PROXY
    value: 1
  - key: IS_DOCKER
    value: true
  - key: SECRET_KEY
    generateValue: false  #original true
  - key: DEPLOYMENT
    value: render

#- type: worker
 # name: asg-rinzler
 # env: docker
 # dockerfilePath: ./worker/Dockerfile
 # dockerContext: ./worker
 # numInstances: 1
 # autoDeploy: false
 # envVars:
 # - key: IS_DOCKER
 #   value: true
 # - key: SECRET_KEY
 #   generateValue: true
 # - key: DEPLOYMENT
 #   value: render
