services:
- type: web
  name: posthog
  env: docker
  dockerfilePath: ./server/Dockerfile
  dockerContext: ./server
  envVars:
    - key: IS_BEHIND_PROXY
      value: 1
    - key: POSTHOG_REDIS_HOST
      fromService:
        name: posthog-redis
        type: pserv
        property: host
    - key: POSTHOG_REDIS_PORT
      fromService:
        name: posthog-redis
        type: pserv
        property: port
    - key: DATABASE_URL
      fromDatabase:
        name: posthog
        property: connectionString

- type: pserv
  name: posthog-redis
  env: docker
  repo: https://github.com/render-examples/redis.git
  disk:
    name: data
    mountPath: /var/lib/redis
    sizeGB: 10

databases:
- name: posthog
  databaseName: posthog
  user: posthog

- type: worker
  name: posthog-worker
  env: docker
  dockerfilePath: ./worker/Dockerfile
  dockerContext: ./worker
  numInstances: 1
  envVars:
    - key: POSTHOG_REDIS_HOST
      fromService:
        name: posthog-redis
        type: pserv
        property: host
    - key: POSTHOG_REDIS_PORT
      fromService:
        name: posthog-redis
        type: pserv
        property: port
    - key: DATABASE_URL
      fromDatabase:
        name: posthog
        property: connectionString

# See https://render.com/docs/deploy-posthog#scaling-posthogs-worker
# if you need to scale the background worker and replace the worker service
# above with the two services below:
#  - type: worker-beat
#    name: posthog-worker-beat
#    env: docker
#    dockerfilePath: ./worker-beat/Dockerfile
#    dockerContext: ./worker-beat
#    numInstances: 1
#    envVars:
#      - key: POSTHOG_REDIS_HOST
#        fromService:
#          name: posthog-redis
#          type: pserv
#          property: host
#      - key: POSTHOG_REDIS_PORT
#        fromService:
#          name: posthog-redis
#          type: pserv
#          property: port
#      - key: DATABASE_URL
#        fromDatabase:
#          name: posthog
#          property: connectionString
#
#  - type: worker-celery
#    name: posthog-worker-celery
#    env: docker
#    dockerfilePath: ./worker-celery/Dockerfile
#    dockerContext: ./worker-celery
#    envVars:
#      - key: POSTHOG_REDIS_HOST
#        fromService:
#          name: posthog-redis
#          type: pserv
#          property: host
#      - key: POSTHOG_REDIS_PORT
#        fromService:
#          name: posthog-redis
#          type: pserv
#          property: port
#      - key: DATABASE_URL
#        fromDatabase:
#          name: posthog
#          property: connectionString
