databases:
- name: posthog
  databaseName: posthog
  user: posthog
  plan: standard # posthog can quickly use up hundreds of MBs of disk space

services:
- type: web
  name: posthog
  env: docker
  dockerfilePath: ./server/Dockerfile
  dockerContext: ./server
  autoDeploy: false
  envVars:
  - key: IS_BEHIND_PROXY
    value: 1
  - key: PORT
    value: 8000
  - key: POSTHOG_REDIS_HOST
    fromService:
      name: posthog-redis
      type: pserv
      property: host
  - key: POSTHOG_REDIS_PORT
    fromService:
      name: posthog-redis
      type: pserv
      property: port
  - key: DATABASE_URL
    fromDatabase:
      name: posthog
      property: connectionString
  - key: SECRET_KEY
    generateValue: true

- type: pserv
  name: posthog-redis
  env: docker
  autoDeploy: false
  repo: https://github.com/render-examples/redis.git
  disk:
    name: data
    mountPath: /var/lib/redis
    sizeGB: 10

- type: worker
  name: posthog-worker
  env: docker
  dockerfilePath: ./worker/Dockerfile
  dockerContext: ./worker
  numInstances: 1
  autoDeploy: false
  envVars:
  - key: POSTHOG_REDIS_HOST
    fromService:
      name: posthog-redis
      type: pserv
      property: host
  - key: POSTHOG_REDIS_PORT
    fromService:
      name: posthog-redis
      type: pserv
      property: port
  - key: DATABASE_URL
    fromDatabase:
      name: posthog
      property: connectionString
  - key: SECRET_KEY
    generateValue: true
